name: "publish to docker"
description: "build a container image and pushes it to docker"

inputs:
  registry_username:
    description: "username for image registry"
    required: true
  registry_password:
    description: "passwprd for image registry"
    required: true
  image_name:
    description: "name of the image registry"
    required: true        
  tag:
    description: "how to tag the image. Default: latest"

runs:
  using: composite
  steps:
    - name: setup buildx
      uses: docker/setup-buildx-action@v1

    - name: login to the registry
      uses: docker/login-action@v1
      with:
        username: ${{inputs.registry_username}}
        password: ${{inputs.registry_password}}

    - name: set the tag
      shell: bash
      run: |
        if [ -z "${{inputs.tag}}"]
        then
          echo "final_tag=latest" >> $GITHUB_ENV
        else
          echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
        fi

    - name: Build and Push the Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{inputs.registry_username}}/${{inputs.image_name}}:${{env.final_tag}}

    - name: pwd
      run: |
        pwd
      shell: bash
